### ISSUE TITLE
Kapt is not able process .

### ISSUE THREAD

**Issue by tapanrgohil** [aniketbhoite/Assume#15]
Caused by: java.lang.NullPointerException
	at com.aniketbhoite.assume.processor.ProcessorUtilKt.kotlinClassMetadata(ProcessorUtil.kt:12)
	at com.aniketbhoite.assume.processor.AssumeProcessor.process(AssumeProcessor.kt:63)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:89)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor

**Comment by aniketbhoite** [comment]
Please share the following details
- Assume Version
- Kotlin Version
- Other Annotation processors you might be using
- Version of kotlinx-metadata-jvm library you added manually or by any other library

Meanwhile, try following things to fix this if you can
- Update Kotlin version to 1.5.10+
- Assume to latest version 1.1
- If you have any other annotations processor lib like a dagger, Moshi etc. update them to latest version

**Comment by aniketbhoite** [comment]
Closing this due no activity.
@tapanrgohil if issue still persist, raise again with requested details
